# Generated by Django 4.2.7 on 2024-01-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_order_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
