# Generated by Django 4.2.7 on 2024-02-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_article_descrition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='presentation',
            field=models.CharField(default='null', max_length=150, verbose_name='Presentacion'),
        ),
    ]
